#
# Makefile for Phoenix-RTOS telit-le910 driver
#
# Copyright 2018, 2019, 2020 Phoenix Systems
#

NAME := telit-le910
LOCAL_SRCS := telit-le910.c
DEP_LIBS := libhostproxy
DEPS := common

include $(binary.mk)
