#
# Makefile for Phoenix-RTOS telit-le910 driver
#
# Copyright 2018, 2019, 2020 Phoenix Systems
#

$(PREFIX_PROG)telit-le910: $(PREFIX_O)drivers/telit-le910_host/telit-le910.o $(PREFIX_A)libhostproxy.a $(PREFIX_A)libusbcdc.a
	$(LINK)

all: $(PREFIX_PROG_STRIPPED)telit-le910

