#
# Makefile for Phoenix-RTOS libusb
#
# Copyright 2025 Phoenix Systems
#

NAME := libusb
LOCAL_PATH := $(call my-dir)
LOCAL_SRCS := cdc_client.c hid_client.c driver.c procdriver.c internal.c devinfo.c
LOCAL_CFLAGS := -I$(LOCAL_PATH)

include $(static-lib.mk)
