#
# Makefile for Phoenix-RTOS telit-le910 driver
#
# Copyright 2018, 2019, 2020 Phoenix Systems
#

$(PREFIX_PROG)umass: $(PREFIX_O)drivers/umass_host/umass.o $(PREFIX_A)libhostproxy.a
	$(LINK)

all: $(PREFIX_PROG_STRIPPED)umass

