#
# Makefile for Phoenix-RTOS cdc demo
#
# Copyright 2020 Phoenix Systems
#

NAME := cdc-demo
LOCAL_SRCS := cdc_demo.c
DEP_LIBS := libusbclass
DEPS := common
LIBS := libusbclient

include $(binary.mk)
