#
# Makefile for Phoenix-RTOS imx6ull ehci
#
# Copyright 2018 Phoenix Systems
#

PROGS_SRCS = usbd.c
PROGS = usb
LDLIBS += -lehci-imx6ull

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
