#
# Makefile for Phoenix-RTOS usb class lib
#
# Copyright 2020-2021 Phoenix Systems
#

NAME := libusbclass
LOCAL_HEADERS := cdc_client.h hid_client.h
LOCAL_SRCS := cdc_client.c hid_client.c
DEPS := common

include $(static-lib.mk)
